version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - sleep
      - infinity

  pg_admin:
    image: quay.io/icecavern/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=pass1234

      
